In [1]:
import numpy as np

In [2]:
def rads(deg):
    return np.radians(deg)

def degrees(rads):
    return np.degrees(rads)

def cos(deg):
    return np.cos(deg)

def sin(deg):
    return np.sin(deg)

def get_transformation(angle, dx, dy):
    return np.array([[cos(angle), 0, sin(angle), dx],
                    [0, 1, 0, 0], 
                    [-1*sin(angle), 0, cos(angle), dy],
                    [0, 0, 0, 1]])

def get_transformation_1(angle, dx, dy):
    return np.array([[cos(angle), -1*sin(angle), 0, dx], 
                    [sin(angle), cos(angle), 0, dy],
                    [0, 0, 1, 0],
                    [0, 0, 0, 1]])


In [3]:
T0_1 = get_transformation_1(phi[0], 0, 0)
print(T0_1)
T1_2 = get_transformation(phi[1], 0, l1)
print(T1_2)
T2_3 = get_transformation(phi[2], 0, l2)
# print(T2_3)
T3_4 = get_transformation(phi[3], 0, l3)
T4_5 = get_transformation(0, 0, l4)

T0_2 = np.dot(T0_1, T1_2)
T0_3 = np.dot(T0_2, T2_3)
T0_4 = np.dot(T0_3, T3_4)
T0_5 = np.dot(T0_4, T4_5)
print(T0_5)
v = np.array([0,0,0,1])
print(np.dot(T0_5, v))

NameError: name 'phi' is not defined

In [4]:
def e(phi):
    T0_1 = get_transformation_1(phi[0], 0, 0)
    # print(T0_1)
    T1_2 = get_transformation(phi[1], 0, l1)
    # print(T1_2)
    T2_3 = get_transformation(phi[2], 0, l2)
    # print(T2_3)
    T3_4 = get_transformation(phi[3], 0, l3)
    T4_5 = get_transformation(0, 0, l4)

    T0_2 = np.dot(T0_1, T1_2)
    T0_3 = np.dot(T0_2, T2_3)
    T0_4 = np.dot(T0_3, T3_4)
    T0_5 = np.dot(T0_4, T4_5)
    v = np.array([0,0,0,1])
    # print(T0_5)
    # print(np.dot(T0_5,v))
    return np.dot(T0_5,v)
    # print(e)



In [5]:
phi = np.array([0, np.pi/4, np.pi/4, np.pi/4])
# phi1 = 0
# phi2 = np.pi/4
# phi3 = np.pi/4
# phi4 = np.pi/4
l1 = 6
l2 = 6
l3 = 1
l4 = 1

In [6]:
p5 = e(phi)
print(p5)


[5.94974747 0.         9.53553391 1.        ]


In [7]:
# n_phi = np.array([phi[0]+rads(0.05),0,0,0])
delt_i = rads(0.05)
# print(f'delt_i: {delt_i}')
d_phi = np.array([delt_i, 0, 0, 0])
num1 = e(phi+d_phi)
num2 = e(phi)
# print(num1)
# print(num2)
de_dphi_1 = (num1-num2)/delt_i
print(de_dphi_1)
# print(de_dphi)


[-2.59606691e-03  5.94974671e+00  0.00000000e+00  0.00000000e+00]


In [10]:
delt_i = rads(0.05)
# print(f'delt_i: {delt_i}')
d_phi = np.array([0, delt_i, 0, 0])
num1 = e(phi+d_phi)
num2 = e(phi)
# print(num1)
# print(num2)
de_dphi_2 = (num1-num2)/delt_i
print(de_dphi_2)

[ 3.53293739  0.         -5.95128938  0.        ]


In [12]:
delt_i = rads(0.05)
# print(f'delt_i: {delt_i}')
d_phi = np.array([0, 0, delt_i, 0])
num1 = e(phi+d_phi)
num2 = e(phi)
# print(num1)
# print(num2)
de_dphi_3 = (num1-num2)/delt_i
print(de_dphi_3)

[-0.70785156  0.         -1.70679803  0.        ]


In [14]:
delt_i = rads(0.05)
# print(f'delt_i: {delt_i}')
d_phi = np.array([0, 0, 0, delt_i])
num1 = e(phi+d_phi)
num2 = e(phi)
# print(num1)
# print(num2)
de_dphi_4 = (num1-num2)/delt_i
print(de_dphi_4)

[-0.70741522  0.         -0.70679816  0.        ]


In [41]:

de_dphi = np.ndarray((4,4))
d_phi = np.zeros(4);
for i in range(4):
    d_phi[i] =  delt_i
    num1 = e(phi+d_phi)
    num2 = e(phi)
    de_dphi[i]= (num1-num2)/delt_i

# print(de_dphi)
de_dphi = de_dphi.transpose()
print(de_dphi)


[[-2.59606691e-03  5.94974671e+00  0.00000000e+00  0.00000000e+00]
 [ 3.53033998e+00  5.95282978e+00 -5.95128938e+00  0.00000000e+00]
 [ 2.82099950e+00  5.95221077e+00 -7.65746904e+00  0.00000000e+00]
 [ 2.11235203e+00  5.95159235e+00 -8.36303145e+00  0.00000000e+00]]
[[-2.59606691e-03  3.53033998e+00  2.82099950e+00  2.11235203e+00]
 [ 5.94974671e+00  5.95282978e+00  5.95221077e+00  5.95159235e+00]
 [ 0.00000000e+00 -5.95128938e+00 -7.65746904e+00 -8.36303145e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [15]:
dim = len(de_dphi_4)
J = np.array([[de_dphi_1[:dim-1]],[de_dphi_2[:dim-1]],[de_dphi_3[:dim-1]],[de_dphi_4[:dim-1]]])
J = np.transpose(J)
J = np.reshape(J, (3,4))
print(J)

[[-2.59606691e-03  3.53293739e+00 -7.07851557e-01 -7.07415225e-01]
 [ 5.94974671e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -5.95128938e+00 -1.70679803e+00 -7.06798158e-01]]


In [16]:
J_pinv = np.linalg.pinv(J)
print(J_pinv)

[[ 8.05906404e-17  1.68074382e-01  4.77404216e-17]
 [ 1.47760232e-01  6.44725678e-05 -7.97554592e-02]
 [-4.01983770e-01 -1.75398519e-04 -2.43933297e-01]
 [-2.73428544e-01 -1.19305717e-04 -1.54226932e-01]]


In [24]:
my_phi = np.array([rads(0.003), rads(0.003), rads(0.003), rads(0.003)])
my_p5 = e(my_phi)
print(my_p5)

[5.75958651e-04 3.01571245e-08 1.40000000e+01 1.00000000e+00]


In [28]:
de = my_p5[:3]
print(de)
# de = my_p5
pred_phi = np.dot(J_pinv, de)

print(pred_phi)

[5.75958651e-04 3.01571245e-08 1.40000000e+01]
[ 5.06864072e-09 -1.11649132e+00 -3.41529768e+00 -2.15933452e+00]


In [131]:
np.pi/4

0.7853981633974483